services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: igmail
    labels:
      - "ig=true"
    # The FQDN (Fully Qualified Domain Name) of your mail server
    hostname: node47.internet-goods.com
    env_file: mailserver.env
    ports:
      - "25:25"    # SMTP
      - "465:465"  # ESMTP (Implicit TLS)
      - "587:587"  # ESMTP (Explicit TLS/STARTTLS)
      - "993:993"  # IMAP4 (Implicit TLS)
    volumes:
      - ./mail-data/:/var/mail/
      - ./mail-state/:/var/mail-state/
      - ./mail-logs/:/var/log/mail/
      - ./mail-config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN # Required for Fail2Ban
    networks:
      - sobridge
networks:
  sobridge:
    name: sobridge
    external: true
